/*
 * @Author: Anscor
 * @Date: 2020-05-04 10:42:17
 * @LastEditors: Anscor
 * @LastEditTime: 2020-05-07 17:48:47
 * @Description: file content
 */


export const STATISTICS_FETCH_USERS = "STATISTICS_FETCH_USERS";
export const STATISTICS_SET_USERS = "STATISTICS_SET_USERS";
export const STATISTICS_SELECTED_USERS_CHANGED = "STATISTICS_SELECTED_USERS_CHANGED";
export const STATISTICS_SET_TABLE_SCROLL_Y = "STATISTICS_SET_TABLE_SCROLL_Y";
export const STATISTICS_SET_STATISTICS = "STATISTICS_SET_STATISTICS";
