# Generated by Django 3.0.4 on 2020-04-06 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_set_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='题目集id')),
                ('name', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='题目集名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='题目集描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_problem_sets', to=settings.AUTH_USER_MODEL, verbose_name='创建者id')),
            ],
            options={
                'verbose_name': '题目集',
                'verbose_name_plural': '题目集',
                'db_table': 'problem_set',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_set', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='题目id')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='题目名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='题目描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_problems', to=settings.AUTH_USER_MODEL, verbose_name='创建者id')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_problems', to=settings.AUTH_USER_MODEL, verbose_name='更新者id')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'problem',
            },
        ),
    ]
