# Generated by Django 3.0.4 on 2020-04-06 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='题目id'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.ProblemSet', verbose_name='题目集id'),
            preserve_default=False,
        ),
    ]
