# Generated by Django 3.0.4 on 2020-04-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20200406_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='label',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='题目Label'),
        ),
    ]
