# Generated by Django 3.0.4 on 2020-03-28 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('student_id', models.PositiveIntegerField(default=0, verbose_name='学号')),
                ('sex', models.BooleanField(choices=[(False, '女'), (True, '男')], default=True, verbose_name='性别')),
                ('name_pinyin', models.CharField(max_length=64, verbose_name='姓名拼音')),
                ('alias', models.CharField(blank=True, max_length=64, null=True, verbose_name='昵称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='创建者id')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_users', to=settings.AUTH_USER_MODEL, verbose_name='更新者id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户属性表',
                'verbose_name_plural': '用户属性表',
                'db_table': 'user_profile',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='创建者id')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.Group', verbose_name='组id')),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_groups', to='auth.Group', verbose_name='父组id')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_groups', to=settings.AUTH_USER_MODEL, verbose_name='更新者id')),
            ],
            options={
                'verbose_name': '组属性表',
                'verbose_name_plural': '组属性表',
                'db_table': 'group_profile',
                'ordering': ['group_id'],
            },
        ),
    ]
