# Generated by Django 3.0.4 on 2020-03-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name_pinyin',
        ),
    ]
