# Generated by Django 3.0.4 on 2020-04-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(default='未知', max_length=2, verbose_name='性别'),
        ),
    ]
