/*
 * @Author: Anscor
 * @Date: 2020-04-13 18:07:54
 * @LastEditors: Anscor
 * @LastEditTime: 2020-05-08 11:09:56
 * @Description: 提交模块action
 */

export const SUBMISSION_FETCH_ALL_USER = "SUBMISSION_FETCH_ALL_USER";
export const SUBMISSION_SET_USERS = "SUBMISSION_SET_USERS";
export const SUBMISSION_FETCH_SUBMISSIONS = "SUBMISSION_FETCH_SUBMISSIONS";
export const SUBMISSION_FETCH_SUBMISSIONS_SUCCESS = "SUBMISSION_FETCH_SUBMISSIONS_SUCCESS";
export const SUBMISSION_DETAIL_MODAL_CLOSE = "SUBMISSION_DETAIL_MODAL_CLOSE";
export const SUBMISSION_DETAIL_CLICK = "SUBMISSION_DETAIL_CLICK";
export const SUBMISSION_TEXT_CMP_MODAL_CLOSE = "SUBMISSION_TEXT_CMP_MODAL_CLOSE";
export const SUBMISSION_TEXT_CMP_CLICK = "SUBMISSION_TEXT_CMP_CLICK";
export const SUBMISSION_FETCH_TEXT_CMP_SUCCESS = "SUBMISSION_FETCH_TEXT_CMP_SUCCESS";
export const SUBMISSION_SYNTAX_CMP_CLICK = "SUBMISSION_SYNTAX_CMP_CLICK";
export const SUBMISSION_SYNTAX_CMP_MODAL_CLOSE = "SUBMISSION_SYNTAX_CMP_MODAL_CLOSE";
export const SUBMISSION_FETCH_SYNTAX_CMP_SUCCESS = "SUBMISSION_FETCH_SYNTAX_CMP_SUCCESS";
