# Generated by Django 3.0.4 on 2020-04-06 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField(blank=True, null=True, verbose_name='运行id')),
                ('code', models.TextField(verbose_name='代码')),
                ('result', models.CharField(max_length=64, verbose_name='结果')),
                ('memory', models.IntegerField(verbose_name='使用内存')),
                ('time', models.IntegerField(verbose_name='使用时间')),
                ('language', models.CharField(max_length=16, verbose_name='语言')),
                ('compile_error_info', models.TextField(blank=True, null=True, verbose_name='编译错误信息')),
                ('ip', models.CharField(blank=True, max_length=128, null=True, verbose_name='ip地址')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submit_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '提交',
                'verbose_name_plural': '提交',
                'db_table': 'submission',
            },
        ),
    ]
