# Generated by Django 3.0.4 on 2020-04-06 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_label'),
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submissions', to='problems.Problem'),
            preserve_default=False,
        ),
    ]
