# Generated by Django 3.0.4 on 2020-04-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_submission_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTextLineCmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='序号')),
                ('old_line_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='原代码行号')),
                ('old_line', models.TextField(blank=True, null=True, verbose_name='原代码行')),
                ('old_symbol', models.CharField(default='b', max_length=1, verbose_name='原代码记号')),
                ('new_line_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='新代码行号')),
                ('new_line', models.TextField(blank=True, null=True, verbose_name='新代码行')),
                ('new_symbol', models.CharField(default='b', max_length=1, verbose_name='新代码记号')),
            ],
            options={
                'verbose_name': '代码纯文本行对比',
                'verbose_name_plural': '代码纯文本行对比',
                'db_table': 'code_text_line_cmp',
                'managed': False,
            },
        ),
    ]
