# Generated by Django 3.0.4 on 2020-04-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_codetextlinecmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='rid',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='运行id'),
        ),
    ]
