# Generated by Django 3.0.4 on 2020-04-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0004_auto_20200418_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSyntaxLineCmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='序号')),
                ('old_line_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='原代码行号')),
                ('old_line', models.TextField(blank=True, null=True, verbose_name='原代码行')),
                ('new_line_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='新代码行号')),
                ('new_line', models.TextField(blank=True, null=True, verbose_name='新代码行')),
                ('is_same', models.BooleanField(default=False, verbose_name='语法成分是否相同')),
            ],
            options={
                'verbose_name': '代码语法行对比',
                'verbose_name_plural': '代码语法行对比',
                'db_table': 'code_syntax_line_cmp',
                'managed': False,
            },
        ),
    ]
