# Generated by Django 3.0.4 on 2020-05-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0005_codesyntaxlinecmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='rid',
        ),
    ]
